### ISSUE TITLE
Upgrade to use syncano-js v1

### ISSUE THREAD

**Issue by zachgarwood** [zachgarwood/ember-syncano#2]
Currently, the addon is pinned to "^0.4.4" (see [here](https://github.com/Syncano/ember-syncano/blob/master/blueprints/ember-syncano/index.js)). Upgrade to use the stable v1 release. There were significant changes to the API in the update to v1, so this will require a considerable overhaul.

**Comment by twack05** [comment]
Version 0.2.0 resolves this.

**Comment by zachgarwood** [comment]
Nice!
